You had a HEAD tag showing up at the top of the file.
nzufelt/open_source_movement_csc630 pull request #74
Opened 2018-02-03 02:18 UTC by naluconcepcion

Not sure if this was intentional, but I commented the lines out for now.

2018-02-03 21:17 UTC, ruddfawcett commented
Definitely not intentional — could you remove them in a new commit (sorry not at a computer right now)?

2018-02-03 22:30 UTC, milesmcc requested changes
This is definitely a residual merge conflict. Perhaps line 9 should also be removed so that there are not duplicate imports?

2018-02-03 22:30 UTC, milesmcc commented on essays.html
>      <link rel="stylesheet" type="text/css" href='./assets/styles/main.css' />
This code seems identical to line 7—perhaps this should be removed as well?

2018-02-09 04:07 UTC, nzufelt commented
I think this is resolved by #84.  Closing for now, reopen if needed.

2018-02-09 04:07 UTC, closed without merging