Page titles & HEAD displaying at the top of essays.html
nzufelt/open_source_movement_csc630 pull request #77
Opened 2018-02-04 16:45 UTC by ahmetoguzlu

A weird HEAD was being displayed at the top of essays.html. Essays, Git
Cheatsheet and Projects tabs displayed “Assignments” in the title.

2018-02-07 18:16 UTC, sam-xif commented
The HEAD looks like it was from a resiidual merge conflict. The only problem is that now the line `<link rel="stylesheet" type="text/css" href="./assets/styles/main.css" />` shows up twice in the file.

The rest of this PR looks good.

2018-02-07 20:30 UTC, milesmcc requested changes

2018-02-07 20:30 UTC, milesmcc commented on essays.html
>      <link rel="stylesheet" type="text/css" href='./assets/styles/main.css' />
duplicate; consider removing?

2018-02-20 23:18 UTC, ruddfawcett commented
Thanks!

2018-02-20 23:18 UTC, merged